"""add price alerts

Revision ID: 639714c79ac0
Revises: ffd7f8e8f042
Create Date: 2026-04-03 16:25:49.891537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639714c79ac0'
down_revision = 'ffd7f8e8f042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sneaker_id', sa.Integer(), nullable=True),
    sa.Column('model_keyword', sa.String(length=100), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sneaker_id'], ['sneakers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_alerts')
    # ### end Alembic commands ###
