"""create sneaker table

Revision ID: c3b3dd58be4c
Revises: 
Create Date: 2026-03-22 03:36:59.942716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b3dd58be4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sneakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('condition_grade', sa.String(length=50), nullable=False),
    sa.Column('original_box', sa.Boolean(), nullable=True),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('avg_market_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image_front', sa.String(length=255), nullable=True),
    sa.Column('image_side', sa.String(length=255), nullable=True),
    sa.Column('image_sole', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sneakers')
    # ### end Alembic commands ###
